rw_blog:
    resource: "@RwBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
login:
    pattern:   /login
    defaults:  { _controller: RwUserBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

